services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./backend/qdrant_storage:/qdrant/storage
    environment:
      - QDRANT_URL=http://qdrant:6333
      - DATABASE_HOST=mysql_container
      - DATABASE_USER=tronggg
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=mydatabase
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 10s
      retries: 5
    networks:
      - my_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
    - mysql
    - qdrant
    environment:
      - QDRANT_URL=http://qdrant:6333
      - DATABASE_HOST=mysql_container
      - DATABASE_USER=tronggg
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=mydatabase
      # - PYTHONUNBUFFERED=1
    networks:
      - my_network
    volumes:
      - ./images:/app/images


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
    - backend
    command: streamlit run ./app.py --server.port=8501 --server.address=0.0.0.0
    environment:
      - QDRANT_URL=http://qdrant:6333
      - DATABASE_HOST=mysql_container
      - DATABASE_USER=tronggg
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=mydatabase
    networks:
      - my_network

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: tronggg
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql_container
      - PMA_PORT=3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - my_network

networks:
  my_network:

volumes:
  mysql_data:
  qdrant_data:
