use financial;

ALTER TABLE profit_loss CHANGE COLUMN `CP` `stock_code` VARCHAR(10);
ALTER TABLE profit_loss CHANGE COLUMN `Năm` `year` BIGINT;
ALTER TABLE profit_loss CHANGE COLUMN `Tăng trưởng doanh thu (%)` `revenue_growth` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Doanh thu (Tỷ đồng)` `revenue` BIGINT;
ALTER TABLE profit_loss CHANGE COLUMN `Lợi nhuận sau thuế của Cổ đông công ty mẹ (Tỷ đồng)` `net_profit_after_tax_for_parent_company` BIGINT;
ALTER TABLE profit_loss CHANGE COLUMN `Tăng trưởng lợi nhuận (%)` `profit_growth` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Thu nhập tài chính` `financial_income` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Doanh thu bán hàng và cung cấp dịch vụ` `sales_revenue` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Các khoản giảm trừ doanh thu` `revenue_deductions` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Doanh thu thuần` `net_revenue` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Giá vốn hàng bán` `cost_of_goods_sold` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Lãi gộp` `gross_profit` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Chi phí tài chính` `financial_expenses` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Chi phí bán hàng` `sales_expenses` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Chi phí quản lý DN` `management_expenses` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Lãi/Lỗ từ hoạt động kinh doanh` `operating_profit_loss` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Thu nhập khác` `other_income` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Thu nhập/Chi phí khác` `other_income_expenses` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Lợi nhuận khác` `other_profit` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `LN trước thuế` `profit_before_tax` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Chi phí thuế TNDN hiện hành` `current_tax_expenses` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Chi phí thuế TNDN hoãn lại` `deferred_tax_expenses` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Lợi nhuận thuần` `net_profit_final` BIGINT;
ALTER TABLE profit_loss CHANGE COLUMN `Cổ đông của Công ty mẹ` `parent_company_shareholders` BIGINT;
ALTER TABLE profit_loss CHANGE COLUMN `Ticker` `ticker_symbol` TEXT;
ALTER TABLE profit_loss CHANGE COLUMN `Chi phí tiền lãi vay` `interest_expenses` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Lãi/lỗ từ công ty liên doanh` `profit_loss_from_joint_ventures` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Lãi lỗ trong công ty liên doanh, liên kết` `profit_loss_from_associates` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Cổ đông thiểu số` `minority_shareholders` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Thu nhập lãi và các khoản tương tự` `interest_and_related_income` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Chi phí lãi và các khoản tương tự` `interest_and_related_expenses` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Thu nhập lãi thuần` `net_interest_income` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Thu nhập từ hoạt động dịch vụ` `service_revenue` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Chi phí hoạt động dịch vụ` `service_expenses` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Lãi thuần từ hoạt động dịch vụ` `net_service_profit` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Kinh doanh ngoại hối và vàng` `forex_and_gold_trading` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Chứng khoán kinh doanh` `trading_securities` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Chứng khoán đầu tư` `investment_securities` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Hoạt động khác` `other_operations` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Chi phí hoạt động khác` `other_operating_expenses` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Lãi/lỗ thuần từ hoạt động khác` `net_profit_loss_from_other_operations` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Cố tức đã nhận` `dividends_received` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Tổng thu nhập hoạt động` `total_operating_income` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `LN từ HĐKD trước CF dự phòng` `operating_profit_before_provision` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Chi phí dự phòng rủi ro tín dụng` `credit_risk_provision_expenses` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Thuế TNDN` `corporate_income_tax` DOUBLE;
ALTER TABLE profit_loss CHANGE COLUMN `Lãi cơ bản trên cổ phiếu` `basic_eps` DOUBLE;
